# Generated by Django 4.1.5 on 2023-01-07 03:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='dealers_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))]),
        ),
    ]
